# Generated by Django 5.2 on 2025-05-08 04:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studycollections', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multiplechoicequestion',
            name='collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mcqs', to='studycollections.collection'),
        ),
    ]
