# Generated by Django 5.2 on 2025-05-15 16:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studycollections', '0003_collaborationinvite'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='viewers',
            field=models.ManyToManyField(blank=True, related_name='viewable_collections', to=settings.AUTH_USER_MODEL),
        ),
    ]
