# Generated by Django 5.2 on 2025-05-23 18:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studycollections', '0005_document'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='reports',
        ),
        migrations.AddField(
            model_name='document',
            name='reports',
            field=models.ManyToManyField(blank=True, related_name='reported_documents', to=settings.AUTH_USER_MODEL),
        ),
    ]
