# Generated by Django 5.2 on 2025-04-17 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_document_status_alter_document_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='reports',
            field=models.JSONField(default=list),
        ),
    ]
